### ISSUE TITLE
制約が簡単に参照や変更できるようになってほしい

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#141]
現状では、たとえば 1 ≤ N ≤ 20000 という制約があったときに 20000 という数値が `task.md`, `random.cpp`, `verify.cpp` などにそれぞれ即値として 20000 が埋め込まれています。これはミスが生まれやすくてよくないはずです。「よく見たら実は `random.cpp` だけ 2000 になってた」みたいなのが怖くないですか？

現状でもサンプルについては `{{example example_00}}` のように書いて自動で読み込めるようになっています。これと同様に、どこかに定数だけまとめて書いておいて、たとえば `{{param MAX_N}}` で読み込めたり `params.h` のようなファイルが自動生成されるとよいと思います。

**Comment by kmyk** [comment]
これ、たのむ (制約を複数箇所に書くとめちゃミスするので)

---

とりあえず仕様の詳細について検討したいです。具体的には以下はどう思いますか？

-   `info.toml` の中に以下のように書く

    ``` toml
    [params]
    N_MIN = 1
    N_MAX = 500000
    MOD = 998244353
    YES = "Yes"
    NO = ":("
    ```

-   `params.h` という名前のファイルが `info.toml` と同じディレクトリに生成される。`#include "./params.h"` あるいは `#include "../params.h"` して使う
-   `task.md` からは `{{param N_MAX}}` の形で利用する
