### ISSUE TITLE
部分点システム

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#78]
#77 のように、計算量によって実装量が数倍変わるような問題が存在する、こういうのをどうするか？

- このジャッジの思想としては、大きいほうをベリファイできるべき
- 小さいほうの実装がベリファイできないというのは避けたい
  - ICPC等実装量が短い方を選択するシチュエーションはある
  - そもそも大きいほうを書くためには大体小さいほうを書くはずで、そこでベリファイできると精神が安定する

よってこのジャッジとしては大きいほうと小さいほう両方をチェックできる仕組みを導入したい

そこで現状考えているのは2つで、

- 問題を2種類作る
  - general_matching_small  /  general_matching など
- 問題に部分点を導入する
  - AC(oox) みたいに表示する

問題を2種類作る
Pros:
  - 追加の実装が要らない
Cons:
  - 例えばN=1000が限界だと信じてた問題が後年N=100,000で解けることが分かったりしたら、どうするか？

問題に部分点を導入する
Pros:
  - 変更に対して強靭
  - わかりやすい
Cons:
  - どうやって部分点のファイルを指定するのか？採点はどうするのか？など様々な設計の問題が発生

**Comment by hos-lyric** [comment]
とりあえずは，テストケース名から小さいデータで通っていること (やその実行時間) がわかれば満足かなという気持ちでいました

**Comment by yosupo06** [comment]
確かに、現状では優先度低そうで大丈夫ですね

**Comment by yosupo06** [comment]
必要そうな問題が溜まってきたんで、真面目に考えます

**Comment by yosupo06** [comment]
ドラフト

変数名とか深く考えていません

### 要件リスト

- 色んな制約の部分問題を後から追加できるようにしたい(より小さい制約, より大きい制約, はたまたMODが素数とか…)
- task.mdやverify.cppを部分点の個数用意するのはやめたい(problems)
- (問題の種類, 制約)のタプルについて一意なIDを振りたい(N=2000に提出した問題が後日N=200,000でリジャッジされる、とかは避けたい)
- CIとかローカルから回すときは(AC / それ以外)の2値以外は扱いたくない(だろう)

満たしたい条件が多すぎる(素朴)

### library-checker-problems

部分点っぽいものを導入

info.tomlに

```toml
[[subtasks]]
    name = "default"
    case = ['example_00.in', 'small_*.in']
[[subtasks]]
    name = "big"
    case = ['example_*.in', 'small_*.in', 'random_*.in']
```

みたいになんらかのケースの集合を指定する。



### judge.yosupo.jp

(問題, 部分点)ごとに一意なURLか何かを与えないと不都合が生まれないか？
